name: Simple HTML CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Success (Just a dummy message)
        run: echo "🎉 HTML Code Deployed!"
